#Terraform Cloud Deployment for IBM Cloud
name: IBM_Cloud

on:
  push:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TERRAFORM_TOKEN }}
      
      - name: Initialize
        run: terraform init

      - id: Validate
        run: terraform validate

      - id: cd
        run: cd ./platforms/ibm/account/a228f14f7d90d68181aa768db69f6829/cluster

      - id: pwd
        run: pwd

      - id: ls
        run: ls -laR

      - id: Plan
        run: terraform plan -no-color

      - run: echo ${{ steps.plan.outputs.stdout }}
      - run: echo ${{ steps.plan.outputs.stderr }}
      - run: echo ${{ steps.plan.outputs.exitcode }}
